"""add_video_pendinglog_feedback

Revision ID: 636804fc1463
Revises: 
Create Date: 2026-01-04 19:19:28.482825+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '636804fc1463'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create users table first (referenced by others)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('whoop_user_id', sa.String(length=64), nullable=True),
    sa.Column('whoop_tokens_enc', sa.Text(), nullable=True),
    sa.Column('equipment_profile', sa.Enum('HOME_FULL', 'TRAVEL_BANDS', 'TRAVEL_NONE', name='equipmentprofile'), nullable=False),
    sa.Column('hrmax_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('whoop_user_id')
    )
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('pending_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=16), nullable=True),
    sa.Column('kb_weight_kg', sa.Integer(), nullable=True),
    sa.Column('equipment_profile_at_time', sa.Enum('HOME_FULL', 'TRAVEL_BANDS', 'TRAVEL_NONE', name='equipmentprofile'), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_workout_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'MATCHED', 'CONFIRMED', 'CANCELLED', name='pendinglogstate'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('kb_weight_kg IN (12, 20)', name='ck_pending_logs_kb_weight'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_logs_user_created', 'pending_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_pending_logs_user_state', 'pending_logs', ['user_id', 'state'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pending_log_id', sa.Uuid(), nullable=True),
    sa.Column('whoop_workout_id', sa.String(length=64), nullable=True),
    sa.Column('rpe_1_5', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rpe_1_5 BETWEEN 1 AND 5', name='ck_feedback_rpe'),
    sa.ForeignKeyConstraint(['pending_log_id'], ['pending_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_user_created', 'feedback', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_user_created', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_pending_logs_user_state', table_name='pending_logs')
    op.drop_index('ix_pending_logs_user_created', table_name='pending_logs')
    op.drop_table('pending_logs')
    op.drop_table('videos')
    # ### end Alembic commands ###
